name: Android CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


jobs:
  build:

    runs-on: ubuntu-latest

   

    steps:
    - name: Check Mode 
      run: chmod +x gradlew
    - name: Touch local properties
      run: touch local.properties

    - name: Add Api Key
      run: echo "API_KEY=\"\"" >> local.properties
    
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Build with Gradle
      run: ./gradlew build
